if: commit_message !~ /(no-deploy|wip)/
os: linux
language: java
jdk: openjdk11

script:
  - mvn clean package

deploy:
  on:
    branch: master
  edge: true
  provider: lambda
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-east-1
  function_name: bitcoin-price-alert
  module_name: lambdabitcoinpricealert.Handler
  handler_name: handleRequest
  timeout: 15
  memory_size: 512
  runtime: java11
  description: 'Get alerts for bitcoin price changes'
  zip: ./target/lambda-bitcoin-price-alert-1.0.jar
